import type { TranslationResource } from './zh-Hant.ts'

const zhHans = {
  'home.dynamicArtCard': '动态艺术',
  'control.unsupportedAudioFile': '不支持此音频文件，请选择 MP3、M4A、WAV 或 OGG。',
  'control.audioAddFailed': '无法添加音频文件，请重试。',
  'control.linkageCount': '关联 {{count}} 个', 'control.linkageOutgoing': '此物件触发', 'control.linkageIncoming': '控制此物件', 'control.linkageControlledObject': '受控物件', 'control.linkageTemporaryBackgroundShort': '背景跟随', 'control.linkageEditNamed': '编辑 {{name}} 的物件联动', 'control.linkageNoTargets': '尚未设置受控物件', 'control.linkageAdd': '新增关联', 'control.linkageControlledBy': '由其他物件控制', 'control.linkageViewSourceNamed': '查看触发物件 {{name}}', 'control.linkageRelation': '物件关系', 'control.linkageTargetsNamed': '触发：{{names}}', 'control.linkageTargetCountCompact': '触发 {{count}}', 'control.linkageControlledByNamed': '由 {{name}} 控制', 'control.linkageFromCompact': '由 {{name}}', 'control.linkageBothRoles': '触发及受控', 'control.linkageSourceRole': '触发方', 'control.linkageTargetRole': '受控方', 'control.linkageEdit': '编辑物件关系', 'control.linkageCreate': '建立物件关系', 'control.chooseControlledObject': '选择受控物件', 'control.linkageTargetMissing': '没有可用的受控物件。', 'control.linkageBehavior': '受控方式', 'control.linkageSummaryShow': '{{source}} 出场完成后，{{seconds}} 秒后显示 {{target}}。', 'control.linkageSummaryHide': '{{source}} 出场完成后，{{seconds}} 秒后隐藏 {{target}}。', 'control.linkageTemporaryBackground': '受控物件的背景会锁定并跟随触发物件；解除关联后才可单独设置。', 'control.linkageReplaceWarning': '此物件目前由 {{name}} 控制，确认后将替换原关系。', 'control.linkageRemove': '解除关联', 'control.linkageReplace': '替换关系', 'control.linkageUpdate': '更新关系', 'control.linkageConfirm': '建立关系',
  'common.appName': 'MagicFloor', 'common.close': '关闭', 'common.cancel': '取消', 'common.save': '保存', 'common.next': '下一步', 'common.load': '加载', 'common.processing': '处理中', 'common.select': '选择', 'common.backHome': '返回首页', 'common.user': '用户', 'common.signedIn': '已登录', 'common.file': '文件', 'common.back': '返回', 'common.stop': '停止', 'common.done': '完成', 'common.delete': '删除', 'common.selectAll': '全选', 'common.deselectAll': '取消全选', 'common.selectedCount': '已选 {{count}}', 'common.selectNamed': '选择 {{name}}',
  'auth.signIn': '登录', 'auth.signingIn': '登录中', 'auth.signInSuccess': '登录成功', 'auth.email': '电子邮箱', 'auth.password': '密码', 'auth.showPassword': '显示密码', 'auth.hidePassword': '隐藏密码', 'auth.emailRequired': '请输入电子邮箱。', 'auth.passwordRequired': '请输入密码。', 'auth.networkError': '无法连接，请检查网络后重试。', 'auth.invalidCredentials': '电子邮箱或密码不正确。', 'auth.tooManyAttempts': '尝试次数过多，请稍后再试。', 'auth.unavailable': '暂时无法登录，请稍后再试。',
  'home.settings': '设置', 'home.keyboardControl': '键盘控制', 'home.dynamicArt': '动态艺术', 'home.interactiveArt': '互动艺术', 'home.archivePreview': '作品档案预览', 'home.openArchive': '打开 {{name}}', 'home.newArchive': '新作品档案',
  'remoteKeyboard.back': '返回首页', 'remoteKeyboard.title': '键盘控制', 'remoteKeyboard.panel': 'MagicFloor 机械键盘控制器', 'remoteKeyboard.keyEscape': 'Escape', 'remoteKeyboard.keyHome': 'Home', 'remoteKeyboard.keyControlShift': 'Control 与 Shift', 'remoteKeyboard.keyAltF4': 'Alt 与 F4', 'remoteKeyboard.keySpaceN': 'Space 与 N', 'remoteKeyboard.keySpaceF': 'Space 与 F', 'remoteKeyboard.keyEnd': 'End', 'remoteKeyboard.keyPageDown': 'Page Down', 'remoteKeyboard.keyShortcut': '快捷键 {{number}}', 'remoteKeyboard.volumeKnob': '音量控制', 'remoteKeyboard.verticalKnob': '上下控制', 'remoteKeyboard.horizontalKnob': '左右控制',
  'settings.title': '设置', 'settings.close': '关闭设置', 'settings.accountLoading': '正在加载账号资料', 'settings.currentAccount': '当前账号：{{name}}', 'settings.galleryIp': '艺术画廊 IP', 'settings.dynamicPort': '动态艺术端口', 'settings.interactivePort': '互动艺术端口', 'settings.showQrCode': '显示二维码', 'settings.signOut': '退出登录', 'settings.signingOut': '正在退出', 'settings.signOutFailed': '无法退出登录，请稍后再试。', 'settings.language': '界面语言', 'settings.languageTitle': '选择语言', 'settings.backToSettings': '返回设置', 'settings.advancedFeatures': '进阶功能', 'settings.advancedFeaturesSummary': '启用物件音源、背景绑定与进阶转场',
  'directSelect.back': '返回首页', 'directSelect.title': '选择快速上传类型', 'directSelect.section': '互动艺术', 'directSelect.animals': '多种动物', 'directSelect.buildings': '缤纷建筑', 'directSelect.fish': '多种鱼类',
  'directComplete.eyebrow': '快速上传', 'directComplete.title': '上传完成', 'directComplete.previewAlt': '快速上传预览', 'directComplete.result': '结果', 'directComplete.sent': '图片已发送', 'directComplete.unknownFile': '未记录文件名', 'directComplete.backToThemes': '返回选项', 'directComplete.uploadAgain': '重新上传', 'directComplete.uploadAnother': '再上传一张', 'directComplete.reuploadDialogTitle': '再上传一张图片？', 'directComplete.reuploadDialogSafety': '已发送的图片不会受到影响。', 'directComplete.reuploadDialogDestination': '你将返回图片与遮罩选择页，开始另一次上传。', 'directComplete.startUpload': '开始上传',
  'upload.noFile': '未选择文件', 'upload.directHttp': 'HTTP 直传', 'upload.quickPhotoTitle': '快速拍照上传', 'upload.artworkTitle': '上传作品', 'upload.quickEyebrow': '快速上传', 'upload.slotEyebrow': '槽位 {{index}}', 'upload.sendQuick': '上传图片', 'upload.sendGallery': '发送到艺术画廊', 'upload.galleryIp': '艺术画廊 IP',
  'upload.cameraPreviewFailed': '相机预览启动失败，请检查相机权限。', 'upload.audioRecording': '正在录制音频…', 'upload.audioComplete': '录制完成，可发送到艺术画廊。', 'upload.audioFailed': '录制失败，请检查麦克风权限。', 'upload.unsupportedFile': '不支持的文件类型，请选择 JPEG、PNG、GIF 或 WebP。', 'upload.fileTooLarge': '文件过大，请选择 10MB 以内的图片。', 'upload.cameraOpenFailed': '打开相机失败，请检查相机权限。', 'upload.torchToggleFailed': '此相机暂时无法切换闪光灯。', 'upload.photoFailed': '拍照处理失败，请重试。', 'upload.completeFailed': '无法完成，请重试。', 'upload.imageNetworkFailed': '上传失败，请检查图片、遮罩或网络连接。', 'upload.ipNetworkFailed': '上传失败，请检查艺术画廊 IP 或网络连接。', 'upload.sentGallery': '已发送到艺术画廊',
  'upload.methodTitle': '选择上传方式', 'upload.closeMethod': '关闭上传方式', 'upload.photoLibrary': '相册', 'upload.takePhoto': '拍照', 'upload.chooseFile': '选择文件', 'upload.cameraStarting': '正在启动相机', 'upload.maskAlt': '遮罩：{{name}}', 'upload.swipeUpMasks': '上滑选择遮罩', 'upload.mask': '遮罩', 'upload.swipeDownClose': '下滑收起', 'upload.cameraMaskLabel': '拍照定位遮罩', 'upload.closeCamera': '关闭相机', 'upload.turnOffTorch': '关闭闪光灯', 'upload.turnOnTorch': '开启闪光灯', 'upload.torchUnsupported': '此相机不支持闪光灯', 'upload.capture': '拍摄', 'upload.maskAlign': '遮罩对齐', 'upload.chooseQuickMask': '选择快速上传遮罩', 'upload.adjustArtworkMask': '调整作品与遮罩', 'upload.previewAlt': '上传预览', 'upload.chooseImage': '选择图片', 'upload.currentMaskAlt': '当前遮罩：{{name}}', 'upload.noMask': '无遮罩', 'upload.audio': '音频', 'upload.audioRecorded': '已录制音频', 'upload.recording': '录制中', 'upload.record': '录音', 'upload.preview': '预览', 'upload.reselect': '重新选择', 'upload.retake': '重新拍摄', 'upload.chooseQuickImage': '选择快速上传图片', 'upload.chooseArtworkImage': '选择作品图片', 'upload.camera': '相机', 'upload.captureArtwork': '拍摄作品', 'upload.openCamera': '打开相机',
  'groups.folderCount': '{{count}} 个文件夹', 'groups.materialCount': '{{count}} 个素材', 'groups.emptyFolder': '空文件夹', 'groups.materialSummary': '{{backgrounds}} 个背景 · {{objects}} 个物件', 'groups.preview': '{{name}} 预览', 'groups.openMenu': '打开 {{name}} 菜单', 'groups.moreActions': '更多操作', 'groups.folder': '文件夹', 'groups.material': '素材', 'groups.currentPath': '当前路径', 'groups.archive': '作品档案', 'groups.libraryLabel': '作品素材库', 'groups.name': '名称', 'groups.modified': '修改日期', 'groups.type': '类型', 'groups.content': '内容', 'groups.emptyContent': '此文件夹尚未创建内容', 'groups.previousLevel': '上一层', 'groups.viewMode': '查看方式', 'groups.iconMode': '图标模式', 'groups.detailMode': '详细模式', 'groups.sort': '排序', 'groups.newFolder': '新建文件夹', 'groups.newMaterial': '新建素材', 'groups.closeMenu': '关闭菜单', 'groups.entityMenu': '{{name}} 菜单', 'groups.edit': '编辑', 'groups.moveTo': '移动到', 'groups.delete': '删除', 'groups.thumbnailPreview': '缩略图预览', 'groups.chooseThumbnail': '选择缩略图', 'groups.folderName': '文件夹名称', 'groups.materialName': '素材名称', 'groups.folderPlaceholder': '输入文件夹名称', 'groups.materialPlaceholder': '输入素材名称', 'groups.creating': '创建中', 'groups.create': '创建', 'groups.saving': '保存中', 'groups.destination': '目标位置', 'groups.move': '移动', 'groups.confirmDeleteAgain': '再次确认删除', 'groups.deleteQuestion': '删除“{{name}}”？', 'groups.recursiveWarning': '文件夹内的所有素材与子文件夹都将永久删除。', 'groups.folderContents': '包含 {{folders}} 个子文件夹与 {{materials}} 个素材。', 'groups.deleting': '删除中', 'groups.deleteMaterial': '删除素材', 'groups.deleteFolder': '删除文件夹', 'groups.confirmDeleteAll': '确认全部删除', 'groups.moveContentsDelete': '移出内容并删除', 'groups.deleteWithContents': '连同内容删除',
  'sync.starting': '正在同步作品档案', 'sync.background': '正在同步背景 {{current}}/{{total}}', 'sync.item': '正在同步图片 {{current}}/{{total}}', 'sync.parameters': '正在同步作品参数', 'sync.complete': '作品档案已同步', 'sync.failed': '作品档案同步失败，请确认艺术画廊已打开。',
  'items.untitled': '未命名物件', 'items.limitReached': '每个作品档案最多可创建 30 张图片。', 'items.uploadFirst': '请先上传图片。', 'items.confirmDelete': '确定要删除此物件？', 'items.listLabel': '作品图片列表', 'items.add': '新增物件', 'items.addShort': '新增', 'items.closeMenu': '关闭物件菜单', 'items.edit': '编辑物件', 'items.delete': '删除物件', 'items.object': '物件', 'items.imagePreview': '物件图片预览', 'items.uploadImage': '上传图片', 'items.replaceImage': '更换图片', 'items.name': '物件名称', 'items.namePlaceholder': '输入物件名称', 'items.enterControl': '进入控制页',
  'background.back': '返回作品档案', 'background.eyebrow': '动态艺术 · {{name}}', 'background.title': '背景上传', 'background.prompt': '选择图片或视频作为动态艺术背景', 'background.resource': '背景资源', 'background.upload': '上传背景', 'background.select': '选择背景', 'background.current': '当前背景', 'background.video': '视频背景', 'background.image': '图片背景',
  'legacyHome.back': '返回入口', 'legacyHome.title': '作品控制上传', 'legacyHome.ipPlaceholder': '艺术画廊 IP', 'legacyHome.directHttp': 'HTTP 直传', 'legacyHome.selectSlot': '选择一个作品槽位', 'legacyHome.slotHelp': '进入已有作品可直接打开控制页；空槽位会进入上传流程。', 'legacyHome.slots': '作品槽位', 'legacyHome.cached': '{{count}}/20 已缓存', 'legacyHome.selectSlotLabel': '选择作品槽位 {{index}}', 'legacyHome.slotAlt': '作品槽位 {{index}}',
  'orientation.title': '请横屏使用 iPad', 'orientation.body': 'MagicFloor 为横屏控制台设计，请旋转设备继续操作。',
  'theme.ocean': '美丽海洋', 'theme.forest1': '魔幻森林1', 'theme.forest2': '魔幻森林2', 'theme.paintingReal': '画境成真',
  'edit.title': '作品控制', 'edit.gridPosition': '格位 {{index}}', 'edit.stagePreview': '舞台预览', 'edit.stageHelp': '拖动作品定位，双击打开工具', 'edit.releaseSignal': '释放信号', 'edit.controllable': '可控制', 'edit.editingAlt': '正在编辑的作品', 'edit.tools': '工具', 'edit.artworkTools': '作品工具', 'edit.collapse': '收起', 'edit.resetScale': '重置缩放', 'edit.resetRotation': '重置旋转', 'edit.animationNumber': '动画 {{id}}', 'edit.scene': '场景', 'edit.sceneCoral': '海底珊瑚', 'edit.sceneTown': '动物小镇', 'edit.sceneBlank': '空白网格', 'edit.releaseObject': '释放物件', 'edit.resetPosition': '重置位置', 'edit.uploadAgain': '重新上传', 'edit.deleteArtwork': '删除作品', 'edit.confirmDeleteSlot': '确定删除槽位 {{index}} 的作品吗？', 'edit.deleteFailed': '删除作品失败，请稍后再试。',
  'mask.giraffe': '长颈鹿', 'mask.peacock': '孔雀', 'mask.fox': '狐狸', 'mask.zebra': '斑马', 'mask.elephant': '大象', 'mask.deer': '鹿', 'mask.buildingComplex': '建筑群', 'mask.buildingFacade': '建筑立面', 'mask.longBuilding': '长型建筑', 'mask.lShapeBuilding': 'L 型建筑', 'mask.truck': '货车', 'mask.minivan': '厢型车', 'mask.sedan': '轿车', 'mask.compactCar': '小型车', 'mask.marlin': '旗鱼', 'mask.clownfish': '小丑鱼', 'mask.pufferfish': '河豚', 'mask.seahorse': '海马', 'mask.seaTurtle': '海龟', 'mask.squid': '鱿鱼', 'mask.angelfish': '神仙鱼', 'mask.tuna': '金枪鱼', 'mask.shark': '鲨鱼', 'mask.none': '无', 'mask.dinosaur': '恐龙', 'mask.bear': '小熊', 'mask.fish': '鱼', 'mask.fullBody': '全身人形', 'mask.portrait': '人像',
  'control.stopPreview': '停止预览', 'control.appearanceSettings': '出现设置', 'control.editBackground': '编辑背景', 'control.preview': '预览', 'control.chooseBackgroundPrompt': '请新增或选择背景', 'control.stageStructure': '舞台结构', 'control.layers': '图层', 'control.collapseLayers': '收起图层', 'control.expandLayers': '展开图层', 'control.layerSummary': '{{motion}} · 动画 {{animation}}', 'control.openObjectProperties': '打开 {{name}} 的物件属性', 'control.objectProperties': '物件属性', 'control.properties': '属性', 'control.deleteNamed': '删除 {{name}}', 'control.previewNamed': '预览 {{name}}', 'control.previewImage': '预览图片', 'control.cancelRename': '取消修改名称', 'control.saveObjectName': '保存物件名称', 'control.renameNamed': '修改物件名称：{{name}}', 'control.rename': '修改名称', 'control.nameRequired': '名称不能为空', 'control.nameSaveFailed': '无法保存名称，请重试', 'control.backToLayers': '返回图层',
  'control.motion': '移动方式', 'control.motionShort': '移动方式', 'control.animation': '动画', 'control.animationShort': '动画', 'control.size': '大小', 'control.deform': '变形', 'control.deformShort': '变形', 'control.copyProperties': '属性复制', 'control.copyPropertiesShort': '属性复制', 'control.motionNone': '停止', 'control.motionVertical': '上下', 'control.motionLeft': '左移', 'control.motionRight': '右移', 'control.motionOrbit': '360回环', 'control.motionRandom': '随机', 'control.amplitudeTrack': '幅度 {{percent}}% · 轨道 {{track}}', 'control.speedPercent': '速度 {{percent}}%', 'control.trackSelection': '轨道选择', 'control.track': '轨道', 'control.trackTop': '上', 'control.trackMiddle': '中', 'control.trackBottom': '下',
  'control.scale': '缩放', 'control.rotation': '旋转', 'control.flipHorizontal': '水平翻转', 'control.flipVertical': '垂直翻转', 'control.sourceObject': '来源物件', 'control.availableCount': '{{count}} 个可选', 'control.noCopySource': '暂无其他物件可复制。', 'control.propertiesCopied': '属性已复制', 'control.stage': '舞台', 'control.appearSequence': '逐个出现', 'control.appearAll': '全部出现', 'control.intervalSeconds': '间隔 {{value}} 秒', 'control.playInLayerOrder': '按图层顺序播放',
  'control.stageBackground': '舞台背景', 'control.assetCount': '{{count}} 个素材', 'control.closeBackgroundEditor': '关闭编辑背景', 'control.backgroundPlaybackMode': '背景切换方式', 'control.backgroundFixed': '固定背景', 'control.backgroundRandom': '随机切换', 'control.backgroundSequence': '全部切换', 'control.switchInterval': '切换间隔', 'control.backgroundInterval': '背景切换间隔', 'control.backgroundIntervalUnit': '背景切换间隔单位', 'control.seconds': '秒', 'control.minutes': '分钟', 'control.dragBackgroundHint': '按住卡片拖动可调整播放顺序', 'control.noBackgrounds': '尚未添加背景', 'control.deleteSelected': '删除选中项', 'control.addBackground': '新增背景',
  'control.objectPreview': '物件预览', 'control.resetImagePreview': '重置图片预览', 'control.resetPreview': '重置预览', 'control.closeImagePreview': '关闭图片预览', 'control.cancelCopy': '取消复制', 'control.confirmCopyProperties': '确认复制属性', 'control.source': '来源', 'control.target': '目标', 'control.copyContent': '复制内容', 'control.copyReplaceNote': '目标物件所选属性将被替换，其他属性保持不变。', 'control.copying': '正在复制...', 'control.confirmCopy': '确认复制', 'control.copySourceMissing': '无法复制属性，请确认来源物件仍然存在。', 'control.copyFailed': '无法复制属性，请重试。', 'control.confirmDeleteBackgrounds': '确定要删除选中的背景？', 'control.confirmDeleteObjects': '确定要删除选中的 {{count}} 个物件？',
  'control.objectAudio': '物件音源', 'control.objectBackground': '物件背景', 'control.appearAnimation': '出场动画', 'control.appearAnimationNone': '淡入', 'control.appearAnimationDrop': '上方掉落', 'control.appearAnimationTrackSlide': '左右进场', 'control.backgroundTransition': '背景转场', 'control.backgroundTransitionNone': '直接切换', 'control.backgroundTransitionCurtain': '舞台窗帘', 'control.backgroundTransitionCamera': '拍照闪白', 'control.backgroundTransitionShadow': '皮影戏', 'control.applyTransition': '应用转场', 'control.backgroundTransitionSummary': '转场：{{transition}}', 'control.destination': '目标点', 'control.destinationReady': '已设置', 'control.loopMovement': '循环移动', 'control.moveToDestination': '移动到目标点', 'control.setDestination': '设置目标点', 'control.editDestination': '修改目标点', 'control.audioAssigned': '已选音源', 'control.audioNotAssigned': '未选音源', 'control.uploadAudio': '新增音源', 'control.audioUploading': '正在添加', 'control.noAudio': '无音源', 'control.audioFile': '音频文件', 'control.previewAudio': '试听音源', 'control.deleteAudio': '删除音源', 'control.noAudioFiles': '尚未添加音源', 'control.audioPlayback': '播放时机', 'control.audioOnAppearance': '出现时', 'control.audioAfterDelay': '延迟播放', 'control.audioOnArrival': '到达目标', 'control.delaySeconds': '延迟秒数', 'control.targetAudioNeedsDestination': '请先在移动方式中设置目标点。', 'control.allBackgrounds': '所有背景', 'control.specifiedBackgrounds': '指定背景', 'control.selectedBackgroundCount': '已选 {{count}} 个', 'control.objectAcrossAllBackgrounds': '此物件会在所有背景中显示。', 'control.objectOnlyOnSelectedBackgrounds': '此物件只会在已选背景中显示。', 'control.backgroundMusic': '背景音乐', 'control.applyToSelectedBackgrounds': '应用至已选 {{count}} 个背景', 'control.applyToCurrentBackground': '应用至当前背景', 'control.applyMusic': '应用音乐', 'control.clearMusic': '清除音乐', 'control.confirmDeleteAudio': '确定要删除此音源？使用它的背景与物件将取消绑定。', 'control.objectLinkage': '物件联动', 'control.linkageNone': '无', 'control.linkageShowAfter': '指定时间出现', 'control.linkageHideAfter': '指定时间隐藏', 'control.linkageTrigger': '触发物件', 'control.chooseTriggerObject': '选择触发物件', 'control.linkageDelay': '延迟时间', 'control.linkageCycleError': '无法创建循环联动，请选择其他物件。', 'control.linkageTriggerMissing': '没有可用的触发物件。',
  'animation.none': '无动画', 'animation.breathe': '呼吸缩放', 'animation.swing': '摇摆', 'animation.blink': '闪烁', 'animation.rotate': '轻微旋转', 'animation.bounce': '弹跳', 'animation.wave': '波动', 'animation.flip': '快速翻转', 'animation.pulse': '透明脉冲', 'animation.walk': '行走', 'animation.danceOne': '舞动一', 'animation.danceTwo': '舞动二', 'animation.jellyJump': '果冻跳跃', 'animation.jumpFlip': '翻转跳跃', 'animation.pullRight': '向右拉伸', 'animation.raiseHand': '举手', 'animation.rolling': '滚动', 'animation.unityWave': '挥动', 'animation.shortNone': '无', 'animation.shortBreathe': '呼吸', 'animation.shortSwing': '摇摆', 'animation.shortBlink': '闪烁', 'animation.shortRotate': '旋转', 'animation.shortBounce': '弹跳', 'animation.shortWave': '波动', 'animation.shortFlip': '翻转', 'animation.shortPulse': '脉冲', 'animation.shortWalk': '行走', 'animation.shortDanceOne': '舞动一', 'animation.shortDanceTwo': '舞动二', 'animation.shortJellyJump': '果冻', 'animation.shortJumpFlip': '翻跳', 'animation.shortPullRight': '拉伸', 'animation.shortRaiseHand': '举手', 'animation.shortRolling': '滚动', 'animation.shortUnityWave': '挥动', 'animation.preview': '{{name}}预览', 'animation.walkPreview': '行走动画预览', 'animation.namedWalk': '{{name}}行走动画', 'animation.namedPreview': '{{name}}：{{animation}}', 'animation.mode': '动画模式', 'animation.random': '随机动画', 'animation.previous': '上一个动画', 'animation.next': '下一个动画', 'animation.selectedCount': '已选 {{count}} 项', 'animation.clickRange': '点击动画范围', 'animation.clickRangeTitle': '选择点击动画', 'animation.clickRangeHint': '选择此物件在 PC 上被点击时播放的动画。', 'animation.clickRangeConfirm': '应用范围', 'animation.clickRangeCancel': '取消'
} satisfies TranslationResource

export default zhHans
